notifications:
  email: false
branches:
  only:
    - master
language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "P6rr9zRzJfodqw7dCKZAQtBi8rcMwYAhXwyk27k+8tRbKdoMyxPDGByo1EEW\n39Y7W53gmXYgjb6FZcwwJ/d+yr6DpZuxbcGt75HmsHltJPTJB4OzXQCliod+\nMRw6VQmHdnZVMS2yHBc4OXrVfM99o4k2uNcq4dapgX8K3oflY5A="
    - secure: "ZQggUDYRhdI8SCC+VkcKZ8AHV1KlnJzGhsBC2yIhWLJaog1nPR8mXsYrWI2H\njQCxT5aGDng2ho856P5M0LFRYN9Qv2g3XPclq+SjDZubbH9v7rjB0YYpntHz\nxP88ykl5T4wImDmA0j4fmYsdqJwW2XyDgKCk2mjiMJAvtkzbtCI="
    - TIMEOUT=600000
    # - HTTP_TIMEOUT=60000
    - HTTP_RETRIES=3
    - HTTP_RETRY_DELAY=60000
    - DEBUG_CONNECTION=1
    - CONCURRENCY=5
    - VERBOSE=1
    - SAUCE_CONNECT_VERSION='4.3'
  matrix:
    - CONFIG=unit
    - CONFIG=multi
    - CONFIG=chrome
    - CONFIG=firefox
    - CONFIG=explorer    
    - CONFIG=iphone
    - CONFIG=ipad
matrix:
  include:
    - node_js: "0.11"
      env: CONFIG=chrome_e2e
  allow_failures:
    - node_js: "0.11"
      env: CONFIG=chrome_e2e
before_script:
  - sudo sysctl -w net.ipv4.tcp_tw_reuse=1
  - sudo sysctl -w net.ipv4.tcp_tw_recycle=1
  - sudo sysctl -w net.ipv4.tcp_fin_timeout=15
  # - ./node_modules/.bin/install_sauce_connect
  # - ./node_modules/.bin/travis_start_sauce_connect
  - npm install -g gulp mocha bdd-with-opts
  - npm update
script:
  - "gulp travis --config $CONFIG --sauce"

lib/commands.js
