notifications:
  email: false
branches:
  only:
    - master
language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "P6rr9zRzJfodqw7dCKZAQtBi8rcMwYAhXwyk27k+8tRbKdoMyxPDGByo1EEW\n39Y7W53gmXYgjb6FZcwwJ/d+yr6DpZuxbcGt75HmsHltJPTJB4OzXQCliod+\nMRw6VQmHdnZVMS2yHBc4OXrVfM99o4k2uNcq4dapgX8K3oflY5A="
    - secure: "ZQggUDYRhdI8SCC+VkcKZ8AHV1KlnJzGhsBC2yIhWLJaog1nPR8mXsYrWI2H\njQCxT5aGDng2ho856P5M0LFRYN9Qv2g3XPclq+SjDZubbH9v7rjB0YYpntHz\nxP88ykl5T4wImDmA0j4fmYsdqJwW2XyDgKCk2mjiMJAvtkzbtCI="
    - TIMEOUT=600000
    # - HTTP_TIMEOUT=300000
    - HTTP_RETRIES=10
    - HTTP_RETRY_DELAY=10000
    - DEBUG_CONNECTION=1
  matrix:
    - BROWSER=multi
    - BROWSER=chrome
    - BROWSER=firefox
    - BROWSER=explorer
    - BROWSER=iphone
    - BROWSER=ipad
matrix:
  include:
    - node_js: "0.11"
      env: BROWSER=chrome
    # moving android in one job at the end cause it is superslow
    - node_js: "0.10"
      env: BROWSER=all_androids
  allow_failures:
    - node_js: "0.11"
      env: BROWSER=chrome
before_script:
  - "make setup_sauce_connect"
script:
  - "make test_travis"
