language: node_js
node_js:
  - 0.8
env:
  - [
      {secure: "P6rr9zRzJfodqw7dCKZAQtBi8rcMwYAhXwyk27k+8tRbKdoMyxPDGByo1EEW\n39Y7W53gmXYgjb6FZcwwJ/d+yr6DpZuxbcGt75HmsHltJPTJB4OzXQCliod+\nMRw6VQmHdnZVMS2yHBc4OXrVfM99o4k2uNcq4dapgX8K3oflY5A="},
      {secure: "ZQggUDYRhdI8SCC+VkcKZ8AHV1KlnJzGhsBC2yIhWLJaog1nPR8mXsYrWI2H\njQCxT5aGDng2ho856P5M0LFRYN9Qv2g3XPclq+SjDZubbH9v7rjB0YYpntHz\nxP88ykl5T4wImDmA0j4fmYsdqJwW2XyDgKCk2mjiMJAvtkzbtCI="}
    ]
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"
# Install Google Chrome
  - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb"
  - "sudo apt-get install libgconf2-4"
  - "sudo dpkg -i google-chrome*.deb"
  - "sudo apt-get -f install" 
  - "sudo apt-get install chrome"
# Install selenium and chromedriver
  - "./node_modules/.bin/install_selenium"
  - "sleep 5"
#  - "./node_modules/.bin/start_selenium > /dev/null 2>&1 &"
  - "./node_modules/.bin/start_selenium_dev &"
script:
#  - "make test_unit"
#  - "make test_saucelabs"
  - "sleep 10"
  - "make test_local"
after_script:
  - "ls -l ./temp/sv-selenium"
  - "cat /home/travis/build/admc/wd/temp/sv-selenium/chromedriver.log"
  - "./node_modules/.bin/kill_selenium"


