language: node_js
addons:
  sauce_connect: true
node_js:
  - "0.10"
 # - "0.9"
env:
  - [
      {secure: "P6rr9zRzJfodqw7dCKZAQtBi8rcMwYAhXwyk27k+8tRbKdoMyxPDGByo1EEW\n39Y7W53gmXYgjb6FZcwwJ/d+yr6DpZuxbcGt75HmsHltJPTJB4OzXQCliod+\nMRw6VQmHdnZVMS2yHBc4OXrVfM99o4k2uNcq4dapgX8K3oflY5A="},
      {secure: "ZQggUDYRhdI8SCC+VkcKZ8AHV1KlnJzGhsBC2yIhWLJaog1nPR8mXsYrWI2H\njQCxT5aGDng2ho856P5M0LFRYN9Qv2g3XPclq+SjDZubbH9v7rjB0YYpntHz\nxP88ykl5T4wImDmA0j4fmYsdqJwW2XyDgKCk2mjiMJAvtkzbtCI="}
    ]
script:
  # - "make test_unit"
  # - "make test_midway_sauce_connect"
  # - "make test_e2e_sauce"
  - "SAUCE_CONNECT=1 BROWSER=chrome ./node_modules/.bin/mocha test/midway/*-specs.js -g 'back/forward'"
